feat(trs-filer): create TRS-Filer component
elixir-cloud-aai/cloud-components pull request #104
Opened 2023-07-30 18:01 UTC by ltwmori

## Description

This PR implements the TRS-filer component as described in the linked issue.

Fixes issue #97 

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

2023-08-23 14:27 UTC, SalihuDickson requested changes
please create a .gitignore file for your package

2023-08-23 15:24 UTC, ltwmori commented on packages/ecc-client-elixir-trs-filer/src/components/ecc-trs-filer/custom/tooltip/tooltip.template.ts
If you had looked more closely at my components, you would have seen that this component is one of the most frequently used by me.

2023-08-23 15:35 UTC, SalihuDickson commented
this package doesn't follow the naming format of the other packages, is there a particular reason you named it like this?

2023-08-23 15:37 UTC, ltwmori commented
> this package doesn't follow the naming format of the other packages, is there a particular reason you named it like this?

actually I was told to name it like this in the slack. You can refer to the following message https://elixir-cloud.slack.com/archives/C01LU14FZ50/p1684958704099269 --> the second one is `ecc-client-elixir-trs-filer`

2023-08-24 21:49 UTC, SalihuDickson requested changes
great work so far! Let's try to get through these issues so you can merge

2023-08-24 21:49 UTC, SalihuDickson commented on packages/ecc-client-elixir-trs-filer/src/components/ecc-trs-filer/definition/ecc-trs-filer.ts
> +  async loadTools() {
you're querying the server for the tools three times whenever the page is refreshed, once here, once in the "trs.list.ts" file and again in the "trs-classes.ts" file, which is inefficient, especially if the data being queried starts to get large. Is there a particular reason you're doing this?

2023-08-24 21:51 UTC, SalihuDickson commented
in the project folder on your system, go into the "packages/ecc-client-ga4gh-wes" directory and delete the "out-tsc" directory there, it's not supposed to be in the repo, I already deleted it in you branch"

2023-08-25 05:05 UTC, ltwmori commented on packages/ecc-client-elixir-trs-filer/src/components/ecc-trs-filer/custom/copy/copy.ts
> +  @observable text: string;
resolved

2023-08-26 08:45 UTC, ltwmori commented on packages/ecc-client-elixir-trs-filer/src/components/ecc-trs-filer/custom/copy/copy.template.ts
> +      <p>${(x) => x.value}dwdwe</p>
resolved

2023-08-26 08:46 UTC, ltwmori commented on packages/ecc-client-elixir-trs-filer/src/components/ecc-trs-filer/custom/tooltip/tooltip.template.ts
resolved

2023-08-26 20:38 UTC, SalihuDickson approved these changes
you can go ahead and merge this and create a new PR for any modifications, this one is already large enough. Great work by the way, while I still have quite concerns we can address in subsequent PRs, your component has come together really well.

2023-08-27 14:05 UTC, merged