feat: add details component
elixir-cloud-aai/cloud-components pull request #198
Opened 2023-11-22 20:07 UTC by JaeAeich

## Description

Add details component

Fixes #196 

## Checklist

- [ ] My code follows the [contributing guidelines][contributing] of this project.
- [ ] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have updated the user-facing documentation to describe any new or changed behavior.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

2023-11-24 21:45 UTC, SalihuDickson reviewed
LGTM. I just have a few minor fixes, I went ahead and made a PR to avoid the back and forth, review and merge at #204 so i can approve this and unblock you.

2023-11-25 20:46 UTC, SalihuDickson commented
hey, @JaeAeich. If this PR isn't done maybe convert it to a draft first to separate it from PRs that need to be reviewed ASAP.

2023-11-28 20:19 UTC, JaeAeich commented
@git-anurag-hub @SalihuDickson please review so I can merge. Hope its fine that we can incrementally add better css and responsive support in other PR, maybe someone can take that up as a new issue.

2023-11-30 11:03 UTC, SalihuDickson requested changes

2023-11-30 11:03 UTC, SalihuDickson commented on apps/documentation/docs/design/components/details.md
> +| `size`    | `false`  | `'medium'`  | `String`  | The size of the button. Possible values: `'small'`, `'medium'`, `'large'`.                       |
the type here shouldn't be string it should be `small | meduim | large`

2023-11-30 12:55 UTC, JaeAeich commented on apps/documentation/docs/design/components/details.md
> +| `value`                   | `true`   |         | `String` or `Number`  | The info to be rendered                         |
done

2023-11-30 12:56 UTC, JaeAeich commented on packages/ecc-utils-design/src/components/details/details.ts
> +  icon?: {
yeah I initially tried that but it was giving error as that slot had to be fixed in slot of shoelace. Maybe we can fixed that later if its not acceptable.

2023-11-30 12:56 UTC, JaeAeich commented on packages/ecc-utils-design/src/components/details/details.ts
> +  // eslint-disable-next-line class-methods-use-this
done

2023-12-01 15:54 UTC, SalihuDickson approved these changes
I'll go ahead and open an issue for the icons, just so we remember to fix it

2023-12-01 15:54 UTC, merged