feat: add code editor
elixir-cloud-aai/cloud-components pull request #222
Opened 2024-01-12 12:49 UTC by JaeAeich

## Description
This PR is to add `code` component to `design` package which could be used to handle code-editing.

Fixes #174 #178

## Checklist

- [x] My code follows the [contributing guidelines][contributing] of this project.
- [x] I am aware that all my commits will be squashed into a single commit, using the PR title as the commit message.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code in hard-to-understand areas.
- [x] I have updated the user-facing documentation to describe any new or changed behavior.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have not reduced the existing code coverage.

## Comments

[contributing]: CONTRIBUTING.md

2024-03-06 04:56 UTC, JaeAeich commented
@git-anurag-hub @SalihuDickson please review this PR!

2024-03-09 11:40 UTC, SalihuDickson requested changes
Great work @JaeAeich, this looks good. Let's resolve these issues and merge ASAP

2024-03-09 11:40 UTC, SalihuDickson commented on packages/ecc-client-lit-ga4gh-tes/src/components/tes-create-run/create-run.ts
it seems the changes in this file are of the eslint issue we just fixed, where we agreed to not selectively disable eslint on different lines of code.Could you please revert the changes made here

2024-03-09 11:40 UTC, SalihuDickson commented on packages/ecc-utils-design/demo/index.html
the file was just formatted by prettier, please revert.

2024-03-09 11:40 UTC, SalihuDickson commented on packages/ecc-utils-design/package.json
the packages with the versions of `*` should not have been changed, they're supposed to match the versions in the root. Please revert the versions of those packages to `*`

2024-03-09 11:40 UTC, SalihuDickson commented on packages/ecc-utils-design/src/components/code/code.ts
> +type Language = "YAML" | "JSON" | "Text";
export type.

2024-03-09 12:02 UTC, SalihuDickson commented on packages/ecc-utils-design/demo/index.html
Also might be a good idea for us write a prettier config (or just adapt one from another project) so that we stop making unnecessary formats like this.

2024-03-10 07:58 UTC, JaeAeich commented on packages/ecc-utils-design/demo/index.html
I added code comp that what its showing, but I agree that we should have a prettier config.

2024-03-10 08:03 UTC, JaeAeich commented on packages/ecc-client-lit-ga4gh-tes/src/components/tes-create-run/create-run.ts
done

2024-03-10 08:03 UTC, JaeAeich commented on packages/ecc-utils-design/src/components/code/code.ts
> +type Language = "YAML" | "JSON" | "Text";
done

2024-03-13 22:22 UTC, SalihuDickson approved these changes

2024-03-13 22:23 UTC, merged