feat(ls-login-button component): this pr initializes package for ecc-…
elixir-cloud-aai/cloud-components pull request #67
Opened 2023-06-17 14:39 UTC by tanya17-05

fix #66 

## Description
initializes package for ecc-client-ga4gh-ls-login web component

## Checklist
> Please go through the following checklist to ensure that your change is ready
> for review. Please do not forget to double check the list after you have
> modified your PR, e.g., if you have added commits to address reviewer
> comments or to fix failing automated checks. Please check items also if they
> do not apply to your change, e.g., if your change does not require an update
> of the user-facing documentation, then still check the box. Generally, PRs
> are only reviewed when all boxes are ticked off and all automated checks pass
> (use the comment section below if you believe that your PR is ready to be
> merged even though not all boxes were ticked off).

- [x] My code follows the [contributing guidelines][contributing] of this
      project, including, in particular, with regard to any style guidelines
- [x] The title of my PR complies with the [Conventional Commits
      specification][conventional-commits]; in particular, it clearly indicates
      that a change is a breaking change
- [x] I am aware that all my commits will be squashed into a single commit,
      using the PR title as the commit message.
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have updated the user-facing documentation to describe any new or
      changed behavior
- [x] I have added type annotations for all function/class/method interfaces
      or updated existing ones
- [x] I have provided [JSDoc][jsdoc] block tags for all
      functions/classes/methods or updated existing ones
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage

[all-contributors-bot]: https://allcontributors.org/docs/en/bot/overview
[all-contributors-types]: https://allcontributors.org/docs/en/emoji-key
[contributing]: CONTRIBUTING.md
[conventional-commits]: https://www.conventionalcommits.org/en/v1.0.0/
[jsdoc]: https://jsdoc.app/index.html

2023-06-17 14:50 UTC, JaeAeich commented
@tanya17-05 There are some issues in the FAST config for test, for now, either change the test script to null or use a different config (I did the later and @ltwmori fid the former) :+1:

2023-06-19 13:41 UTC, uniqueg reviewed
@tanya17-05: Thanks a lot. Given that I can only do a high-level review: Could you please add some description to the PR title and ideally include some link where I can try this out?

2023-06-19 16:56 UTC, git-anurag-hub requested changes
Hey @tanya17-05, I have pointed out some of the main & vital changes in the package! Please have a look & fix the configuration!

2023-06-19 16:56 UTC, git-anurag-hub commented on packages/ecc-client-ga4gh-ls-login/README.md
> +TRS component
Correct this please! Also write some docs & scripts!

2023-06-19 16:56 UTC, git-anurag-hub commented on packages/ecc-client-ga4gh-ls-login/package.json
> +        "eslint": "eslint . --ext .ts",
Where in the `main` property? Please add it!

2024-03-22 16:10 UTC, git-anurag-hub commented
Closing this due to inactivity!

2024-03-22 16:11 UTC, closed without merging